#!/usr/bin/env python3
"""
Static site generator for the AIP-C01 study guide.

Reads content fragments from src/content/*.html, wraps each in the shared
shell (nav, header, footer, progress rail) and writes them to docs/ so the
site can be served straight from GitHub Pages.

Also emits docs/all-in-one.html: every page inlined into a single
self-contained file with hash routing, no external requests. That one is
what gets published as a shareable artifact and what you can email to
yourself and open on a plane.

    python3 build.py
"""

from __future__ import annotations

import html
import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).parent
SRC = ROOT / "src"
CONTENT = SRC / "content"
ASSETS = SRC / "assets"
OUT = ROOT / "docs"

SITE_TITLE = "AIP-C01 Field Manual"
SITE_TAGLINE = "AWS Certified Generative AI Developer – Professional"

# (slug, nav label, page title, group, minutes) -- order defines prev/next.
PAGES = [
    ("index",       "Start here",      "Start here",                                  "Orientation", 12),
    ("exam",        "The exam",        "The exam, decoded",                           "Orientation", 18),
    ("studyplan",   "Study plans",     "Study plans: 8-week, 4-week, 10-day",         "Orientation", 10),
    ("foundations", "Module 0",        "Module 0 — From zero: AI and AWS",            "Learn",       95),
    ("domain1",     "Domain 1 · 31%",  "Domain 1 — FM Integration, Data & Compliance", "Learn",      120),
    ("domain2",     "Domain 2 · 26%",  "Domain 2 — Implementation and Integration",   "Learn",      110),
    ("domain3",     "Domain 3 · 20%",  "Domain 3 — AI Safety, Security, Governance",  "Learn",       85),
    ("domain4",     "Domain 4 · 12%",  "Domain 4 — Operational Efficiency & Cost",    "Learn",       60),
    ("domain5",     "Domain 5 · 11%",  "Domain 5 — Testing, Validation, Debugging",   "Learn",       55),
    ("services",    "Service atlas",   "Service atlas and decision tables",           "Reference",   45),
    ("labs",        "Hands-on labs",   "Hands-on labs: build the whole stack",        "Practice",   180),
    ("practice",    "Question bank",   "Question bank and exam simulator",            "Practice",   240),
    ("flashcards",  "Flashcards",      "Flashcards (spaced repetition)",              "Practice",    40),
    ("cheatsheet",  "Cram sheet",      "The cram sheet",                              "Reference",   30),
    ("glossary",    "Glossary",        "Glossary",                                    "Reference",   25),
]

PAGE_BY_SLUG = {p[0]: p for p in PAGES}

CSS_FILES = ["css/style.css"]
JS_FILES = [
    "data/questions.js",
    "data/q-d0.js",
    "data/q-d1.js",
    "data/q-d2.js",
    "data/q-d3.js",
    "data/q-d4.js",
    "data/q-d5.js",
    "data/flashcards.js",
    "data/searchindex.js",   # generated by this script into docs/
    "js/charts.js",
    "js/interactive.js",
    "js/quiz.js",
    "js/app.js",
]


# --------------------------------------------------------------------------
# shell
# --------------------------------------------------------------------------

def nav_html(current: str, single_file: bool) -> str:
    """Sidebar navigation, grouped."""
    out = []
    seen_groups = []
    for slug, label, _title, group, mins in PAGES:
        if group not in seen_groups:
            seen_groups.append(group)
            out.append(f'<div class="nav-group" data-nav-group="{html.escape(group)}">{html.escape(group)}</div>')
        href = f"#/{slug}" if single_file else ("index.html" if slug == "index" else f"{slug}.html")
        cls = "nav-link active" if slug == current else "nav-link"
        out.append(
            f'<a class="{cls}" href="{href}" data-slug="{slug}">'
            f'<span class="nav-dot" data-dot="{slug}"></span>'
            f'<span class="nav-label">{html.escape(label)}</span>'
            f'<span class="nav-mins">{mins}m</span></a>'
        )
    return "\n".join(out)


def prevnext_html(current: str, single_file: bool) -> str:
    idx = [p[0] for p in PAGES].index(current)
    parts = ['<nav class="prevnext">']
    if idx > 0:
        s, lbl = PAGES[idx - 1][0], PAGES[idx - 1][1]
        href = f"#/{s}" if single_file else ("index.html" if s == "index" else f"{s}.html")
        parts.append(f'<a class="pn pn-prev" href="{href}"><span>← Previous</span><strong>{html.escape(lbl)}</strong></a>')
    else:
        parts.append("<span></span>")
    if idx < len(PAGES) - 1:
        s, lbl = PAGES[idx + 1][0], PAGES[idx + 1][1]
        href = f"#/{s}" if single_file else ("index.html" if s == "index" else f"{s}.html")
        parts.append(f'<a class="pn pn-next" href="{href}"><span>Next →</span><strong>{html.escape(lbl)}</strong></a>')
    else:
        parts.append("<span></span>")
    parts.append("</nav>")
    return "\n".join(parts)


HEAD_EXTRA = """<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="dark light">
<meta name="description" content="A complete, beginner-friendly study guide for the AWS Certified Generative AI Developer - Professional (AIP-C01) exam: full curriculum, diagrams, labs and a question bank.">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='8' fill='%2306070a'/%3E%3Cpath d='M16 6L26 12V20L16 26L6 20V12L16 6Z' stroke='%23818cf8' stroke-width='2.2' stroke-linejoin='round' fill='none'/%3E%3Ccircle cx='16' cy='16' r='3.5' fill='%2338bdf8'/%3E%3C/svg%3E">
<script>
(function() {
  try {
    var t = localStorage.getItem('aip.theme');
    if (t) document.documentElement.dataset.theme = JSON.parse(t);
  } catch(e) {}
})();
</script>"""


FOOTER = """<footer class="site-footer">
  <div>
    <strong>Built as a study aid, not as exam content.</strong>
    Every practice question here is original, written against the published AIP-C01 exam guide.
    Nothing on this site is recalled, leaked or reproduced real exam material — using such material
    violates the AWS Certification agreement and gets certifications revoked.
  </div>
  <div class="footer-links">
    <a href="https://aws.amazon.com/certification/certified-generative-ai-developer-professional/" target="_blank" rel="noopener">Official cert page</a>
    <a href="https://docs.aws.amazon.com/pdfs/aws-certification/latest/ai-professional-01/ai-professional-01.pdf" target="_blank" rel="noopener">Official exam guide (PDF)</a>
    <a href="https://skillbuilder.aws/category/exam-prep/generative-ai-developer-professional-AIP-C01" target="_blank" rel="noopener">AWS Skill Builder</a>
  </div>
  <div class="footer-meta">Service behaviour and pricing change fast — always confirm against current AWS docs before an exam booking.</div>
</footer>"""


def render_app_shell(slug: str, group: str, page_title: str, mins: int, main_html: str, single_file: bool) -> str:
    home = "#/index" if single_file else "index.html"
    return f"""<div class="app-shell" id="appShell">
  <!-- 1. LEFT COMPACT ICON DOCK -->
  <nav class="icon-dock" id="iconDock" aria-label="Quick Navigation Dock">
    <a class="dock-brand" href="{home}" title="AIP-C01 Field Manual">
      <span class="dock-logo">
        <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M12 2L2 7l10 5 10-5-10-5z"></path>
          <path d="M2 17l10 5 10-5"></path>
          <path d="M2 12l10 5 10-5"></path>
        </svg>
      </span>
    </a>
    
    <div class="dock-divider"></div>
    
    <div class="dock-items">
      <button class="dock-btn{' active' if group == 'Orientation' else ''}" data-dock-group="Orientation" title="Orientation (Start, Exam, Plans)">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"></polygon></svg>
      </button>
      <button class="dock-btn{' active' if group == 'Learn' else ''}" data-dock-group="Learn" title="Curriculum (Module 0, Domains 1–5)">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path></svg>
      </button>
      <button class="dock-btn{' active' if group == 'Practice' else ''}" data-dock-group="Practice" title="Practice &amp; Simulator (Labs, Questions, Flashcards)">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="16 18 22 12 16 6"></polyline><polyline points="8 6 2 12 8 18"></polyline></svg>
      </button>
      <button class="dock-btn{' active' if group == 'Reference' else ''}" data-dock-group="Reference" title="Reference (Atlas, Cram Sheet, Glossary)">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="3" y1="9" x2="21" y2="9"></line><line x1="9" y1="21" x2="9" y2="9"></line></svg>
      </button>
    </div>
    
    <div class="dock-spacer"></div>
    
    <div class="dock-bottom">
      <button class="dock-btn" id="cmdBtnDock" title="Command Palette (⌘K)" aria-label="Open Command Palette">
        <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
      </button>
      <button class="dock-btn" id="themeCycleBtn" title="Cycle Theme (Carbon / Titanium / Paper)" aria-label="Cycle Theme">
        <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"></circle><path d="M12 2v2"></path><path d="M12 20v2"></path><path d="m4.93 4.93 1.41 1.41"></path><path d="m17.66 17.66 1.41 1.41"></path><path d="M2 12h2"></path><path d="M20 12h2"></path><path d="m6.34 17.66-1.41 1.41"></path><path d="m19.07 4.93-1.41 1.41"></path></svg>
      </button>
      <button class="dock-btn" id="drawerToggleBtn" title="Toggle Sidebar Drawer ([)" aria-label="Toggle Sidebar Drawer">
        <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="9" y1="3" x2="9" y2="21"></line></svg>
      </button>
    </div>
  </nav>

  <!-- 2. COLLAPSIBLE SIDEBAR DRAWER -->
  <aside class="sidebar-drawer" id="sidebarDrawer">
    <div class="drawer-header">
      <div class="drawer-title">
        <span class="guide-badge">AIP-C01</span>
        <strong>Field Manual</strong>
      </div>
      <button class="drawer-close-btn" id="drawerCloseBtn" title="Close Sidebar ([)" aria-label="Close sidebar">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
      </button>
    </div>

    <div class="progress-card">
      <div class="ring-wrap">
        <svg class="ring" viewBox="0 0 44 44">
          <circle class="ring-bg" cx="22" cy="22" r="19"></circle>
          <circle class="ring-fg" id="ringFg" cx="22" cy="22" r="19"></circle>
        </svg>
        <span id="ringPct">0%</span>
      </div>
      <div class="progress-meta">
        <strong id="progressLabel">Exam Readiness</strong>
        <span id="progressSub">0 of 0 sections read</span>
      </div>
    </div>

    <nav class="drawer-nav">{nav_html(slug, single_file)}</nav>

    <div class="drawer-footer">
      <button class="reset-btn" id="resetProgress">Reset progress</button>
    </div>
  </aside>

  <!-- 3. CENTRAL WORKBENCH -->
  <div class="workbench" id="workbench">
    <header class="workbench-bar">
      <div class="bar-left">
        <button class="icon-btn mobile-menu-btn" id="menuBtn" aria-label="Open Navigation">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
        </button>
        <div class="bar-breadcrumb" id="barBreadcrumb">
          <span class="bc-group">{html.escape(group)}</span>
          <span class="bc-sep">/</span>
          <span class="bc-page">{html.escape(page_title)}</span>
        </div>
      </div>
      <div class="bar-right">
        <button class="cmd-trigger" id="cmdTriggerBtn" aria-label="Search manual">
          <svg class="cmd-icon" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
          <span class="cmd-placeholder">Search manual, questions, labs…</span>
          <kbd class="cmd-shortcut">⌘K</kbd>
        </button>
        <div class="theme-select-wrap">
          <button class="theme-badge-btn" id="themeSelectBtn" title="Switch Theme">
            <span class="theme-dot"></span>
            <span id="themeNameLabel">Carbon</span>
          </button>
        </div>
      </div>
    </header>

    <main class="content-stage" id="contentStage">
      {main_html}
      {FOOTER}
    </main>

    <!-- 4. BOTTOM FLOATING STATUS PILL -->
    <aside class="floating-status-pill" id="floatingPill" aria-label="Reading Status HUD">
      <div class="pill-section pill-meta">
        <span class="pill-dot"></span>
        <span class="pill-title">{html.escape(page_title)}</span>
        <span class="pill-time">≈{mins}m</span>
      </div>
      <div class="pill-sep"></div>
      <div class="pill-section pill-progress">
        <div class="pill-bar-track"><div class="pill-bar-fill" id="pillBarFill"></div></div>
        <span id="pillReadCount">0 read</span>
      </div>
      <div class="pill-sep"></div>
      <div class="pill-section pill-actions">
        <button class="pill-btn" id="pillMarkBtn" title="Mark this page read">Mark page read</button>
        <button class="pill-btn pill-btn-icon" id="pillCmdBtn" title="Command Palette (⌘K)"><kbd>⌘K</kbd></button>
      </div>
    </aside>
  </div>
</div>

<!-- 5. RAYCAST / LINEAR SPOTLIGHT COMMAND PALETTE MODAL -->
<div class="cmd-modal-backdrop" id="cmdModalBackdrop" hidden>
  <div class="cmd-palette-box" role="dialog" aria-modal="true" aria-label="Command Palette">
    <div class="cmd-palette-header">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
      <input class="cmd-palette-input" id="cmdInput" type="text" placeholder="Search manual, questions, labs, or commands..." autocomplete="off" spellcheck="false">
      <kbd class="cmd-palette-esc">ESC</kbd>
    </div>
    <div class="cmd-filters" id="cmdFilters">
      <button class="cmd-filter on" data-filter="all">All</button>
      <button class="cmd-filter" data-filter="Orientation">Orientation</button>
      <button class="cmd-filter" data-filter="Learn">Curriculum</button>
      <button class="cmd-filter" data-filter="Practice">Practice &amp; Labs</button>
      <button class="cmd-filter" data-filter="Reference">Reference</button>
    </div>
    <div class="cmd-palette-results" id="cmdResults"></div>
    <div class="cmd-palette-footer">
      <div class="cmd-footer-keys">
        <span><kbd>↑</kbd><kbd>↓</kbd> Navigate</span>
        <span><kbd>↵</kbd> Select</span>
        <span><kbd>ESC</kbd> Dismiss</span>
      </div>
      <div class="cmd-footer-brand">AIP-C01 Field Manual</div>
    </div>
  </div>
</div>
<div class="scrim" id="scrim"></div>
"""


def page_shell(slug: str, title: str, body: str) -> str:
    group = PAGE_BY_SLUG[slug][3]
    mins = PAGE_BY_SLUG[slug][4]
    css = "\n".join(f'<link rel="stylesheet" href="assets/{f}">' for f in CSS_FILES)
    js = "\n".join(f'<script src="assets/{f}" defer></script>' for f in JS_FILES)
    article_html = f"""<article class="page" data-page="{slug}">
{body}
{prevnext_html(slug, False)}
</article>"""
    shell = render_app_shell(slug, group, title, mins, article_html, False)
    return f"""<!doctype html>
<html lang="en" data-theme="carbon">
<head>
<meta charset="utf-8">
<title>{html.escape(title)} · {SITE_TITLE}</title>
{HEAD_EXTRA}
{css}
{js}
</head>
<body data-page="{slug}">
{shell}
</body>
</html>
"""


def inline_css() -> str:
    """All CSS inlined for single-file bundle."""
    return "\n".join((ASSETS / f).read_text() for f in CSS_FILES)


def inline_js(search_js: str) -> list[str]:
    out = []
    for f in JS_FILES:
        src = ASSETS / f
        out.append(src.read_text() if src.exists() else search_js)
    return out


def bundle_shell(sections: str, search_js: str) -> str:
    css = f"<style>{inline_css()}</style>"
    js = "\n".join(f"<script>{part}</script>" for part in inline_js(search_js))
    shell = render_app_shell("index", "Orientation", "Start here", 12, sections, True)
    return f"""<!doctype html>
<html lang="en" data-theme="carbon">
<head>
<meta charset="utf-8">
<title>{SITE_TITLE} · {SITE_TAGLINE}</title>
{HEAD_EXTRA}
{css}
</head>
<body data-page="index" data-spa="1">
{shell}
{js}
</body>
</html>
"""


def artifact_page(sections: str, search_js: str) -> str:
    """Body-only variant for hosts that supply their own <head> wrapper."""
    css = f"<style>{inline_css()}</style>"
    js = "\n".join(f"<script>{part}</script>" for part in inline_js(search_js))
    shell = render_app_shell("index", "Orientation", "Start here", 12, sections, True)
    return f"""<title>{SITE_TITLE} · {SITE_TAGLINE}</title>
{css}
<div id="aip-root" data-page="index" data-spa="1">
{shell}
</div>
<script>
document.body.dataset.spa = '1';
document.body.dataset.page = 'index';
</script>
{js}
"""


# --------------------------------------------------------------------------
# content post-processing
# --------------------------------------------------------------------------

SECTION_RE = re.compile(r'<section\b[^>]*\bid="([^"]+)"[^>]*>')
H2_RE = re.compile(r"<h2[^>]*>(.*?)</h2>", re.S)


NUM_SPAN_RE = re.compile(r'<span class="num">.*?</span>', re.S)


def strip_tags(s: str) -> str:
    s = NUM_SPAN_RE.sub("", s)
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", s)).strip()


def inject_read_toggles(body: str) -> str:
    """Add a 'mark as read' control to every top-level <section id=...>."""
    def repl(m: re.Match) -> str:
        sid = m.group(1)
        return m.group(0) + (
            f'<button class="read-toggle" data-read="{sid}" '
            f'title="Mark this section as read">'
            f'<span class="rt-box"></span><span class="rt-label">Mark read</span></button>'
        )
    return SECTION_RE.sub(repl, body)


def build_toc(body: str) -> str:
    items = []
    for m in SECTION_RE.finditer(body):
        sid = m.group(1)
        tail = body[m.end(): m.end() + 900]
        h = H2_RE.search(tail)
        if not h:
            continue
        items.append(f'<a href="#{sid}" data-toc="{sid}">{html.escape(strip_tags(h.group(1)))}</a>')
    if len(items) < 2:
        return ""
    return '<nav class="toc"><div class="toc-title">On this page</div>' + "".join(items) + "</nav>"


def render_body(slug: str, raw: str) -> str:
    title = PAGE_BY_SLUG[slug][2]
    group = PAGE_BY_SLUG[slug][3]
    mins = PAGE_BY_SLUG[slug][4]
    header = (
        f'<div class="page-head">'
        f'<div class="crumb">{html.escape(group)}</div>'
        f'<h1>{html.escape(title)}</h1>'
        f'<div class="page-meta"><span class="pill">≈{mins} min</span>'
        f'<span class="pill pill-ghost" id="pageReadState-{slug}">not started</span></div>'
        f"</div>"
    )
    toc = build_toc(raw)
    body = inject_read_toggles(raw)

    # A leading .hero block should sit above the table of contents.
    if toc and body.lstrip().startswith('<div class="hero">'):
        end = body.find("</div>\n\n<section")
        if end == -1:
            end = body.find("<section")
            return header + body[:end] + toc + body[end:]
        end += len("</div>")
        return header + body[:end] + toc + body[end:]
    return header + toc + body


def search_rows(slug: str, raw: str) -> list[dict]:
    """Flat search index so search works across pages in the multi-page build."""
    rows = []
    page_title = PAGE_BY_SLUG[slug][2]
    for m in SECTION_RE.finditer(raw):
        sid = m.group(1)
        nxt = SECTION_RE.search(raw, m.end())
        chunk = raw[m.end(): nxt.start() if nxt else len(raw)]
        h = H2_RE.search(chunk)
        rows.append({
            "slug": slug,
            "id": sid,
            "page": page_title,
            "group": PAGE_BY_SLUG[slug][3],
            "title": strip_tags(h.group(1)) if h else sid,
            "text": strip_tags(chunk)[:6000].lower(),
        })
    return rows


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------

def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    shutil.copytree(ASSETS, OUT / "assets")
    (OUT / ".nojekyll").write_text("")

    bodies: dict[str, str] = {}
    index: list[dict] = []
    for slug, _label, title, _group, _mins in PAGES:
        src = CONTENT / f"{slug}.html"
        if not src.exists():
            print(f"  !! missing fragment, stubbing: {src.name}")
            raw = f'<section id="{slug}-todo"><h2>Coming up</h2><p>Not written yet.</p></section>'
        else:
            raw = src.read_text()
        index.extend(search_rows(slug, raw))
        bodies[slug] = render_body(slug, raw)
        (OUT / f"{slug}.html").write_text(page_shell(slug, title, bodies[slug]))

    search_js = "window.AIP_SEARCH = " + json.dumps(index, separators=(",", ":")) + ";\n"
    (OUT / "assets" / "data" / "searchindex.js").write_text(search_js)

    sections = []
    for slug, _label, _title, _group, _mins in PAGES:
        hidden = "" if slug == "index" else " hidden"
        sections.append(
            f'<article class="page" data-page="{slug}"{hidden}>\n'
            f"{bodies[slug]}\n{prevnext_html(slug, True)}\n</article>"
        )
    (OUT / "all-in-one.html").write_text(bundle_shell("\n".join(sections), search_js))
    (OUT / "artifact.html").write_text(artifact_page("\n".join(sections), search_js))

    total = sum(len(bodies[s].encode()) for s in bodies)
    print(f"built {len(PAGES)} pages -> {OUT}   search index: {len(index)} sections")
    print(f"content: {total/1024:.0f} KB   bundle: {(OUT/'all-in-one.html').stat().st_size/1024:.0f} KB")


if __name__ == "__main__":
    main()
